version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: php:5.6.40-zts-stretch
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - .docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9090:9000"
